
-- 1. 과목유형 테이블(TB_CLASS_TYPE)에 아래와 같은 데이터를 입력하시오.
INSERT INTO TB_CLASS_TYPE VALUES(01, '전공필수');
INSERT INTO TB_CLASS_TYPE VALUES(02, '전공선택');
INSERT INTO TB_CLASS_TYPE VALUES(03, '교양필수');
INSERT INTO TB_CLASS_TYPE VALUES(04, '교양선택');
INSERT INTO TB_CLASS_TYPE VALUES(05, '논문지도');

-- 2.
CREATE TABLE TB_학생일반정보
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
   FROM TB_STUDENT;
   
-- 3.
SELECT * FROM TB_STUDENT;
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_PROFESSOR;

CREATE TABLE TB_국어국문학과
AS SELECT STUDENT_NO, STUDENT_NAME, PROFESSOR_NAME
   FROM TB_STUDENT
   JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
   LEFT JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
   WHERE DEPARTMENT_NAME = '국어국문학과';

SELECT * FROM TB_국어국문학과;

-- 4.
UPDATE TB_DEPARTMENT
SET CAPACITY = ROUND(CAPACITY * 1.1, 0);

SELECT * FROM TB_DEPARTMENT;

-- 5. ******************************
UPDATE TB_STUDNET
SET STUDENT_ADDRESS = ''
WHERE STUDETN_NAME = '박건우';

-- 6.
UPDATE TB_STUDENT
SET STUDENT_SSN = SUBSTR(STUDENT_SSN, 1, 6);

SELECT * FROM TB_STUDENT;

-- 7.
SELECT * FROM TB_STUDENT;
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_GRADE;

UPDATE TB_GRADE
SET POINT = 3.5
WHERE (TERM_NO, STUDENT_NO) IN (SELECT TERM_NO, STUDENT_NO 
                                FROM TB_STUDENT
                                JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
                                JOIN TB_GRADE USING (STUDENT_NO)
                                WHERE STUDENT_NAME = '김명훈'
                                AND  TERM_NO = 200501
                                AND DEPARTMENT_NAME = '의학과');
            
-- 8.
DELETE FROM TB_GRADE
WHERE STUDENT_NO IN (SELECT STUDENT_NO
                    FROM TB_STUDENT
                    JOIN TB_GRADE USING (STUDENT_NO)
                    WHERE ABSENCE_YN = 'Y');
